In [2]:
!pip install spacy

Collecting spacy
  Downloading spacy-3.8.11-cp311-cp311-win_amd64.whl.metadata (28 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Downloading spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Downloading murmurhash-1.0.15-cp311-cp311-win_amd64.whl.metadata (2.3 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Downloading cymem-2.0.13-cp311-cp311-win_amd64.whl.metadata (9.9 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Downloading preshed-3.0.12-cp311-cp311-win_amd64.whl.metadata (2.6 kB)
Collecting thinc<8.4.0,>=8.3.4 (from spacy)
  Downloading thinc-8.3.10-cp311-cp311-win_amd64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Downloading wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.4.3 (from spacy)
  Downloading srsly-2.5.2-cp311-cp311-win_amd64.whl.metadata (20 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Downloading catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<0.5.0,>=0.4.2 (from spacy)
  Downloading weasel-0.4.3-py3-none-any.whl.metadata (4.6 kB)
Collecting typer-slim<1.0.0,>=0.3.0 (from spacy)
  Downloading typer_slim-0.24.0-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\dell\anaconda3\lib\site-packages (from spacy) (4.65.0)
Requirement already satisfied: numpy>=1.19.0 in c:\users\dell\anaconda3\lib\site-packages (from spacy) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\dell\anaconda3\lib\site-packages (from spacy) (2.32.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\dell\anaconda3\lib\site-packages (from spacy) (2.12.2)
Requirement already satisfied: jinja2 in c:\users\dell\anaconda3\lib\site-packages (from spacy) (3.1.3)
Requirement already satisfied: setuptools in c:\users\dell\anaconda3\lib\site-packages (from spacy) (68.2.2)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\anaconda3\lib\site-packages (from spacy) (23.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\dell\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.4 in c:\users\dell\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\dell\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\dell\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\dell\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dell\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dell\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dell\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.10.5)
Collecting blis<1.4.0,>=1.3.0 (from thinc<8.4.0,>=8.3.4->spacy)
  Downloading blis-1.3.3-cp311-cp311-win_amd64.whl.metadata (7.7 kB)
Collecting confection<1.0.0,>=0.0.1 (from thinc<8.4.0,>=8.3.4->spacy)
  Downloading confection-0.1.5-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: colorama in c:\users\dell\anaconda3\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Collecting typer>=0.24.0 (from typer-slim<1.0.0,>=0.3.0->spacy)
  Using cached typer-0.24.1-py3-none-any.whl.metadata (16 kB)
Collecting cloudpathlib<1.0.0,>=0.7.0 (from weasel<0.5.0,>=0.4.2->spacy)
  Downloading cloudpathlib-0.23.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\users\dell\anaconda3\lib\site-packages (from weasel<0.5.0,>=0.4.2->spacy) (5.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\dell\anaconda3\lib\site-packages (from jinja2->spacy) (2.1.3)
Collecting click>=8.2.1 (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy)
  Using cached click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\dell\anaconda3\lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (1.5.0)
Requirement already satisfied: rich>=12.3.0 in c:\users\dell\anaconda3\lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (13.3.5)
Collecting annotated-doc>=0.0.2 (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in c:\users\dell\anaconda3\lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\dell\anaconda3\lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\dell\anaconda3\lib\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.1.0)
Downloading spacy-3.8.11-cp311-cp311-win_amd64.whl (15.3 MB)
   ---------------------------------------- 0.0/15.3 MB ? eta -:--:--
    --------------------------------------- 0.3/15.3 MB 9.9 MB/s eta 0:00:02
   - -------------------------------------- 0.7/15.3 MB 8.8 MB/s eta 0:00:02
   -- ------------------------------------- 0.9/15.3 MB 7.0 MB/s eta 0:00:03
   -- ------------------------------------- 1.0/15.3 MB 6.0 MB/s eta 0:00:03
   --- ------------------------------------ 1.2/15.3 MB 5.5 MB/s eta 0:00:03
   --- ------------------------------------ 1.4/15.3 MB 5.2 MB/s eta 0:00:03
   ---- ----------------------------------- 1.6/15.3 MB 5.0 MB/s eta 0:00:03
   ---- ----------------------------------- 1.8/15.3 MB 4.9 MB/s eta 0:00:03
   ---- ----------------------------------- 1.9/15.3 MB 4.9 MB/s eta 0:00:03
   ----- ---------------------------------- 2.1/15.3 MB 4.6 MB/s eta 0:00:03
   ----- ---------------------------------- 2.3/15.3 MB 4.7 MB/s eta 0:00:03
   ------ --------------------------------- 2.4/15.3 MB 4.6 MB/s eta 0:00:03
   ------ --------------------------------- 2.6/15.3 MB 4.4 MB/s eta 0:00:03
   ------- -------------------------------- 2.8/15.3 MB 4.4 MB/s eta 0:00:03
   ------- -------------------------------- 3.0/15.3 MB 4.3 MB/s eta 0:00:03
   -------- ------------------------------- 3.2/15.3 MB 4.4 MB/s eta 0:00:03
   -------- ------------------------------- 3.2/15.3 MB 4.4 MB/s eta 0:00:03
   -------- ------------------------------- 3.3/15.3 MB 4.0 MB/s eta 0:00:04
   --------- ------------------------------ 3.6/15.3 MB 4.2 MB/s eta 0:00:03
   --------- ------------------------------ 3.8/15.3 MB 4.2 MB/s eta 0:00:03
   ---------- ----------------------------- 4.0/15.3 MB 4.1 MB/s eta 0:00:03
   ---------- ----------------------------- 4.2/15.3 MB 4.2 MB/s eta 0:00:03
   ----------- ---------------------------- 4.4/15.3 MB 4.2 MB/s eta 0:00:03
   ----------- ---------------------------- 4.5/15.3 MB 4.1 MB/s eta 0:00:03
   ------------ --------------------------- 4.7/15.3 MB 4.1 MB/s eta 0:00:03
   ------------ --------------------------- 4.9/15.3 MB 4.1 MB/s eta 0:00:03
   ------------ --------------------------- 5.0/15.3 MB 4.0 MB/s eta 0:00:03
   ------------- -------------------------- 5.1/15.3 MB 4.0 MB/s eta 0:00:03
   ------------- -------------------------- 5.2/15.3 MB 3.9 MB/s eta 0:00:03
   -------------- ------------------------- 5.5/15.3 MB 4.0 MB/s eta 0:00:03
   -------------- ------------------------- 5.7/15.3 MB 4.0 MB/s eta 0:00:03
   --------------- ------------------------ 5.8/15.3 MB 3.9 MB/s eta 0:00:03
   --------------- ------------------------ 6.0/15.3 MB 3.9 MB/s eta 0:00:03
   --------------- ------------------------ 6.1/15.3 MB 3.9 MB/s eta 0:00:03
   ---------------- ----------------------- 6.3/15.3 MB 3.9 MB/s eta 0:00:03
   ---------------- ----------------------- 6.5/15.3 MB 3.9 MB/s eta 0:00:03
   ----------------- ---------------------- 6.6/15.3 MB 3.9 MB/s eta 0:00:03
   ----------------- ---------------------- 6.8/15.3 MB 3.9 MB/s eta 0:00:03
   ------------------ --------------------- 7.0/15.3 MB 3.9 MB/s eta 0:00:03
   ------------------ --------------------- 7.2/15.3 MB 3.9 MB/s eta 0:00:03
   ------------------- -------------------- 7.4/15.3 MB 3.9 MB/s eta 0:00:03
   ------------------- -------------------- 7.5/15.3 MB 3.9 MB/s eta 0:00:03
   -------------------- ------------------- 7.7/15.3 MB 3.9 MB/s eta 0:00:02
   -------------------- ------------------- 7.9/15.3 MB 3.9 MB/s eta 0:00:02
   -------------------- ------------------- 8.0/15.3 MB 3.9 MB/s eta 0:00:02
   --------------------- ------------------ 8.2/15.3 MB 3.9 MB/s eta 0:00:02
   --------------------- ------------------ 8.3/15.3 MB 3.8 MB/s eta 0:00:02
   ---------------------- ----------------- 8.5/15.3 MB 3.8 MB/s eta 0:00:02
   ---------------------- ----------------- 8.6/15.3 MB 3.8 MB/s eta 0:00:02
   ---------------------- ----------------- 8.8/15.3 MB 3.8 MB/s eta 0:00:02
   ----------------------- ---------------- 9.0/15.3 MB 3.8 MB/s eta 0:00:02
   ----------------------- ---------------- 9.2/15.3 MB 3.8 MB/s eta 0:00:02
   ------------------------ --------------- 9.3/15.3 MB 3.8 MB/s eta 0:00:02
   ------------------------ --------------- 9.5/15.3 MB 3.8 MB/s eta 0:00:02
   ------------------------- -------------- 9.7/15.3 MB 3.8 MB/s eta 0:00:02
   ------------------------- -------------- 9.9/15.3 MB 3.8 MB/s eta 0:00:02
   -------------------------- ------------- 10.1/15.3 MB 3.8 MB/s eta 0:00:02
   -------------------------- ------------- 10.3/15.3 MB 3.8 MB/s eta 0:00:02
   --------------------------- ------------ 10.4/15.3 MB 3.8 MB/s eta 0:00:02
   --------------------------- ------------ 10.6/15.3 MB 3.7 MB/s eta 0:00:02
   ---------------------------- ----------- 10.8/15.3 MB 3.7 MB/s eta 0:00:02
   ---------------------------- ----------- 11.0/15.3 MB 3.7 MB/s eta 0:00:02
   ----------------------------- ---------- 11.2/15.3 MB 3.7 MB/s eta 0:00:02
   ----------------------------- ---------- 11.3/15.3 MB 3.7 MB/s eta 0:00:02
   ----------------------------- ---------- 11.3/15.3 MB 3.7 MB/s eta 0:00:02
   ----------------------------- ---------- 11.5/15.3 MB 3.6 MB/s eta 0:00:02
   ------------------------------ --------- 11.9/15.3 MB 3.7 MB/s eta 0:00:01
   ------------------------------- -------- 12.1/15.3 MB 3.7 MB/s eta 0:00:01
   ------------------------------- -------- 12.2/15.3 MB 3.7 MB/s eta 0:00:01
   -------------------------------- ------- 12.4/15.3 MB 3.7 MB/s eta 0:00:01
   -------------------------------- ------- 12.6/15.3 MB 3.7 MB/s eta 0:00:01
   --------------------------------- ------ 12.7/15.3 MB 3.7 MB/s eta 0:00:01
   --------------------------------- ------ 12.7/15.3 MB 3.7 MB/s eta 0:00:01
   ---------------------------------- ----- 13.1/15.3 MB 3.7 MB/s eta 0:00:01
   ---------------------------------- ----- 13.3/15.3 MB 3.7 MB/s eta 0:00:01
   ----------------------------------- ---- 13.5/15.3 MB 3.8 MB/s eta 0:00:01
   ----------------------------------- ---- 13.7/15.3 MB 3.8 MB/s eta 0:00:01
   ------------------------------------ --- 13.9/15.3 MB 3.7 MB/s eta 0:00:01
   ------------------------------------ --- 14.0/15.3 MB 3.8 MB/s eta 0:00:01
   ------------------------------------- -- 14.3/15.3 MB 3.7 MB/s eta 0:00:01
   ------------------------------------- -- 14.5/15.3 MB 3.7 MB/s eta 0:00:01
   -------------------------------------- - 14.7/15.3 MB 3.7 MB/s eta 0:00:01
   -------------------------------------- - 14.9/15.3 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  15.0/15.3 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  15.2/15.3 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  15.3/15.3 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 15.3/15.3 MB 3.7 MB/s eta 0:00:00
Downloading catalogue-2.0.10-py3-none-any.whl (17 kB)
Downloading cymem-2.0.13-cp311-cp311-win_amd64.whl (40 kB)
   ---------------------------------------- 0.0/40.1 kB ? eta -:--:--
   ---------------------------------------- 40.1/40.1 kB 1.9 MB/s eta 0:00:00
Downloading murmurhash-1.0.15-cp311-cp311-win_amd64.whl (25 kB)
Downloading preshed-3.0.12-cp311-cp311-win_amd64.whl (117 kB)
   ---------------------------------------- 0.0/117.7 kB ? eta -:--:--
   ---------------------------------------- 117.7/117.7 kB ? eta 0:00:00
Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Downloading spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Downloading srsly-2.5.2-cp311-cp311-win_amd64.whl (654 kB)
   ---------------------------------------- 0.0/654.1 kB ? eta -:--:--
   ----------------------------- --------- 501.8/654.1 kB 10.5 MB/s eta 0:00:01
   ---------------------------------------- 654.1/654.1 kB 8.3 MB/s eta 0:00:00
Downloading thinc-8.3.10-cp311-cp311-win_amd64.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.8 MB 5.9 MB/s eta 0:00:01
   ---------- ----------------------------- 0.5/1.8 MB 4.9 MB/s eta 0:00:01
   -------------- ------------------------- 0.6/1.8 MB 4.5 MB/s eta 0:00:01
   ------------------ --------------------- 0.8/1.8 MB 4.4 MB/s eta 0:00:01
   ---------------------- ----------------- 1.0/1.8 MB 4.3 MB/s eta 0:00:01
   ------------------------- -------------- 1.2/1.8 MB 4.1 MB/s eta 0:00:01
   ----------------------------- ---------- 1.3/1.8 MB 4.3 MB/s eta 0:00:01
   --------------------------------- ------ 1.5/1.8 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 1.7/1.8 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 3.9 MB/s eta 0:00:00
Downloading typer_slim-0.24.0-py3-none-any.whl (3.4 kB)
Downloading wasabi-1.1.3-py3-none-any.whl (27 kB)
Downloading weasel-0.4.3-py3-none-any.whl (50 kB)
   ---------------------------------------- 0.0/50.8 kB ? eta -:--:--
   ---------------------------------------- 50.8/50.8 kB ? eta 0:00:00
Downloading blis-1.3.3-cp311-cp311-win_amd64.whl (6.2 MB)
   ---------------------------------------- 0.0/6.2 MB ? eta -:--:--
   -- ------------------------------------- 0.4/6.2 MB 8.3 MB/s eta 0:00:01
   ---- ----------------------------------- 0.6/6.2 MB 6.7 MB/s eta 0:00:01
   ----- ---------------------------------- 0.8/6.2 MB 5.7 MB/s eta 0:00:01
   ------ --------------------------------- 1.0/6.2 MB 5.3 MB/s eta 0:00:01
   ------- -------------------------------- 1.2/6.2 MB 5.0 MB/s eta 0:00:01
   -------- ------------------------------- 1.4/6.2 MB 4.8 MB/s eta 0:00:01
   --------- ------------------------------ 1.5/6.2 MB 4.7 MB/s eta 0:00:01
   ----------- ---------------------------- 1.7/6.2 MB 4.6 MB/s eta 0:00:01
   ------------ --------------------------- 1.9/6.2 MB 4.5 MB/s eta 0:00:01
   ------------ --------------------------- 1.9/6.2 MB 4.6 MB/s eta 0:00:01
   ------------- -------------------------- 2.1/6.2 MB 4.2 MB/s eta 0:00:01
   --------------- ------------------------ 2.4/6.2 MB 4.3 MB/s eta 0:00:01
   ----------------- ---------------------- 2.6/6.2 MB 4.3 MB/s eta 0:00:01
   ------------------ --------------------- 2.8/6.2 MB 4.3 MB/s eta 0:00:01
   ------------------- -------------------- 3.0/6.2 MB 4.2 MB/s eta 0:00:01
   -------------------- ------------------- 3.2/6.2 MB 4.2 MB/s eta 0:00:01
   --------------------- ------------------ 3.3/6.2 MB 4.2 MB/s eta 0:00:01
   ---------------------- ----------------- 3.5/6.2 MB 4.2 MB/s eta 0:00:01
   ------------------------ --------------- 3.7/6.2 MB 4.2 MB/s eta 0:00:01
   ------------------------- -------------- 3.9/6.2 MB 4.1 MB/s eta 0:00:01
   -------------------------- ------------- 4.1/6.2 MB 4.1 MB/s eta 0:00:01
   --------------------------- ------------ 4.2/6.2 MB 4.2 MB/s eta 0:00:01
   ---------------------------- ----------- 4.4/6.2 MB 4.2 MB/s eta 0:00:01
   ----------------------------- ---------- 4.6/6.2 MB 4.2 MB/s eta 0:00:01
   ------------------------------- -------- 4.8/6.2 MB 4.1 MB/s eta 0:00:01
   -------------------------------- ------- 5.0/6.2 MB 4.1 MB/s eta 0:00:01
   --------------------------------- ------ 5.2/6.2 MB 4.1 MB/s eta 0:00:01
   ---------------------------------- ----- 5.3/6.2 MB 4.1 MB/s eta 0:00:01
   ----------------------------------- ---- 5.5/6.2 MB 4.1 MB/s eta 0:00:01
   ------------------------------------- -- 5.7/6.2 MB 4.1 MB/s eta 0:00:01
   -------------------------------------- - 5.9/6.2 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------  6.1/6.2 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------- 6.2/6.2 MB 4.0 MB/s eta 0:00:00
Downloading cloudpathlib-0.23.0-py3-none-any.whl (62 kB)
   ---------------------------------------- 0.0/62.8 kB ? eta -:--:--
   ---------------------------------------- 62.8/62.8 kB 3.5 MB/s eta 0:00:00
Downloading confection-0.1.5-py3-none-any.whl (35 kB)
Using cached typer-0.24.1-py3-none-any.whl (56 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Using cached click-8.3.1-py3-none-any.whl (108 kB)
Installing collected packages: wasabi, spacy-loggers, spacy-legacy, murmurhash, cymem, cloudpathlib, click, catalogue, blis, annotated-doc, srsly, preshed, typer, confection, typer-slim, thinc, weasel, spacy
  Attempting uninstall: click
    Found existing installation: click 8.1.7
    Uninstalling click-8.1.7:
      Successfully uninstalled click-8.1.7
  Attempting uninstall: typer
    Found existing installation: typer 0.17.4
    Uninstalling typer-0.17.4:
      Successfully uninstalled typer-0.17.4
Successfully installed annotated-doc-0.0.4 blis-1.3.3 catalogue-2.0.10 click-8.3.1 cloudpathlib-0.23.0 confection-0.1.5 cymem-2.0.13 murmurhash-1.0.15 preshed-3.0.12 spacy-3.8.11 spacy-legacy-3.0.12 spacy-loggers-1.0.5 srsly-2.5.2 thinc-8.3.10 typer-0.24.1 typer-slim-0.24.0 wasabi-1.1.3 weasel-0.4.3

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
anaconda-cli-base 0.5.4 requires click<8.2, but you have click 8.3.1 which is incompatible.
chromadb 1.5.2 requires tenacity>=8.2.3, but you have tenacity 8.2.2 which is incompatible.
gtts 2.5.2 requires click<8.2,>=7.1, but you have click 8.3.1 which is incompatible.

In [3]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     --------------------------------------- 0.0/12.8 MB 262.6 kB/s eta 0:00:49
     --------------------------------------- 0.1/12.8 MB 409.6 kB/s eta 0:00:32
     - -------------------------------------- 0.4/12.8 MB 2.2 MB/s eta 0:00:06
     -- ------------------------------------- 0.8/12.8 MB 3.6 MB/s eta 0:00:04
     --- ------------------------------------ 1.0/12.8 MB 3.9 MB/s eta 0:00:04
     --- ------------------------------------ 1.2/12.8 MB 3.7 MB/s eta 0:00:04
     --- ------------------------------------ 1.3/12.8 MB 3.8 MB/s eta 0:00:04
     --- ------------------------------------ 1.3/12.8 MB 3.8 MB/s eta 0:00:04
     ---- ----------------------------------- 1.3/12.8 MB 2.9 MB/s eta 0:00:04
     ----- ---------------------------------- 1.8/12.8 MB 3.6 MB/s eta 0:00:04
     ------ --------------------------------- 2.0/12.8 MB 3.8 MB/s eta 0:00:03
     ------ --------------------------------- 2.2/12.8 MB 3.7 MB/s eta 0:00:03
     ------- -------------------------------- 2.4/12.8 MB 3.7 MB/s eta 0:00:03
     ------- -------------------------------- 2.5/12.8 MB 3.8 MB/s eta 0:00:03
     ------- -------------------------------- 2.5/12.8 MB 3.8 MB/s eta 0:00:03
     ------- -------------------------------- 2.5/12.8 MB 3.8 MB/s eta 0:00:03
     -------- ------------------------------- 2.6/12.8 MB 3.1 MB/s eta 0:00:04
     -------- ------------------------------- 2.7/12.8 MB 3.2 MB/s eta 0:00:04
     -------- ------------------------------- 2.8/12.8 MB 3.1 MB/s eta 0:00:04
     -------- ------------------------------- 2.8/12.8 MB 3.1 MB/s eta 0:00:04
     -------- ------------------------------- 2.8/12.8 MB 3.1 MB/s eta 0:00:04
     --------- ------------------------------ 3.1/12.8 MB 2.9 MB/s eta 0:00:04
     ----------- ---------------------------- 3.5/12.8 MB 3.2 MB/s eta 0:00:03
     ----------- ---------------------------- 3.8/12.8 MB 3.3 MB/s eta 0:00:03
     ----------- ---------------------------- 3.8/12.8 MB 3.3 MB/s eta 0:00:03
     ----------- ---------------------------- 3.8/12.8 MB 3.3 MB/s eta 0:00:03
     ----------- ---------------------------- 3.8/12.8 MB 3.3 MB/s eta 0:00:03
     ------------ --------------------------- 3.9/12.8 MB 2.9 MB/s eta 0:00:04
     ------------ --------------------------- 4.1/12.8 MB 3.0 MB/s eta 0:00:03
     ------------ --------------------------- 4.1/12.8 MB 3.0 MB/s eta 0:00:03
     ------------ --------------------------- 4.1/12.8 MB 3.0 MB/s eta 0:00:03
     ------------- -------------------------- 4.2/12.8 MB 2.8 MB/s eta 0:00:04
     ------------- -------------------------- 4.2/12.8 MB 2.7 MB/s eta 0:00:04
     ------------- -------------------------- 4.5/12.8 MB 2.7 MB/s eta 0:00:04
     -------------- ------------------------- 4.6/12.8 MB 2.8 MB/s eta 0:00:03
     -------------- ------------------------- 4.6/12.8 MB 2.8 MB/s eta 0:00:03
     -------------- ------------------------- 4.7/12.8 MB 2.7 MB/s eta 0:00:04
     --------------- ------------------------ 4.9/12.8 MB 2.8 MB/s eta 0:00:03
     ---------------- ----------------------- 5.3/12.8 MB 2.9 MB/s eta 0:00:03
     ----------------- ---------------------- 5.6/12.8 MB 3.0 MB/s eta 0:00:03
     ----------------- ---------------------- 5.7/12.8 MB 3.0 MB/s eta 0:00:03
     ----------------- ---------------------- 5.7/12.8 MB 3.0 MB/s eta 0:00:03
     ----------------- ---------------------- 5.7/12.8 MB 2.8 MB/s eta 0:00:03
     ------------------ --------------------- 6.0/12.8 MB 2.9 MB/s eta 0:00:03
     ------------------- -------------------- 6.3/12.8 MB 3.0 MB/s eta 0:00:03
     -------------------- ------------------- 6.5/12.8 MB 3.0 MB/s eta 0:00:03
     -------------------- ------------------- 6.5/12.8 MB 3.0 MB/s eta 0:00:03
     -------------------- ------------------- 6.5/12.8 MB 3.0 MB/s eta 0:00:03
     -------------------- ------------------- 6.7/12.8 MB 2.9 MB/s eta 0:00:03
     --------------------- ------------------ 6.9/12.8 MB 2.9 MB/s eta 0:00:03
     ---------------------- ----------------- 7.1/12.8 MB 3.0 MB/s eta 0:00:02
     ---------------------- ----------------- 7.1/12.8 MB 3.0 MB/s eta 0:00:02
     ---------------------- ----------------- 7.1/12.8 MB 2.8 MB/s eta 0:00:03
     ---------------------- ----------------- 7.3/12.8 MB 2.8 MB/s eta 0:00:02
     ----------------------- ---------------- 7.6/12.8 MB 2.9 MB/s eta 0:00:02
     ------------------------ --------------- 7.9/12.8 MB 3.0 MB/s eta 0:00:02
     ------------------------- -------------- 8.2/12.8 MB 3.0 MB/s eta 0:00:02
     ------------------------- -------------- 8.3/12.8 MB 3.1 MB/s eta 0:00:02
     ------------------------- -------------- 8.3/12.8 MB 3.1 MB/s eta 0:00:02
     ------------------------- -------------- 8.3/12.8 MB 3.1 MB/s eta 0:00:02
     ------------------------- -------------- 8.3/12.8 MB 3.1 MB/s eta 0:00:02
     -------------------------- ------------- 8.4/12.8 MB 2.9 MB/s eta 0:00:02
     -------------------------- ------------- 8.6/12.8 MB 2.9 MB/s eta 0:00:02
     -------------------------- ------------- 8.6/12.8 MB 2.9 MB/s eta 0:00:02
     -------------------------- ------------- 8.6/12.8 MB 2.9 MB/s eta 0:00:02
     --------------------------- ------------ 8.7/12.8 MB 2.8 MB/s eta 0:00:02
     --------------------------- ------------ 8.9/12.8 MB 2.8 MB/s eta 0:00:02
     --------------------------- ------------ 8.9/12.8 MB 2.8 MB/s eta 0:00:02
     --------------------------- ------------ 8.9/12.8 MB 2.8 MB/s eta 0:00:02
     --------------------------- ------------ 8.9/12.8 MB 2.8 MB/s eta 0:00:02
     --------------------------- ------------ 8.9/12.8 MB 2.8 MB/s eta 0:00:02
     ---------------------------- ----------- 9.2/12.8 MB 2.7 MB/s eta 0:00:02
     ----------------------------- ---------- 9.5/12.8 MB 2.8 MB/s eta 0:00:02
     ------------------------------ --------- 9.7/12.8 MB 2.8 MB/s eta 0:00:02
     ------------------------------- -------- 10.0/12.8 MB 2.8 MB/s eta 0:00:01
     ------------------------------- -------- 10.2/12.8 MB 2.9 MB/s eta 0:00:01
     ------------------------------- -------- 10.2/12.8 MB 2.9 MB/s eta 0:00:01
     ------------------------------- -------- 10.2/12.8 MB 2.9 MB/s eta 0:00:01
     ------------------------------- -------- 10.2/12.8 MB 2.9 MB/s eta 0:00:01
     -------------------------------- ------- 10.3/12.8 MB 2.8 MB/s eta 0:00:01
     -------------------------------- ------- 10.4/12.8 MB 2.8 MB/s eta 0:00:01
     -------------------------------- ------- 10.4/12.8 MB 2.8 MB/s eta 0:00:01
     -------------------------------- ------- 10.4/12.8 MB 2.8 MB/s eta 0:00:01
     --------------------------------- ------ 10.6/12.8 MB 2.7 MB/s eta 0:00:01
     --------------------------------- ------ 10.9/12.8 MB 2.7 MB/s eta 0:00:01
     ---------------------------------- ----- 11.1/12.8 MB 2.7 MB/s eta 0:00:01
     ---------------------------------- ----- 11.1/12.8 MB 2.7 MB/s eta 0:00:01
     ---------------------------------- ----- 11.1/12.8 MB 2.7 MB/s eta 0:00:01
     ---------------------------------- ----- 11.2/12.8 MB 2.6 MB/s eta 0:00:01
     ----------------------------------- ---- 11.5/12.8 MB 2.6 MB/s eta 0:00:01
     ------------------------------------ --- 11.8/12.8 MB 2.7 MB/s eta 0:00:01
     ------------------------------------- -- 12.1/12.8 MB 2.7 MB/s eta 0:00:01
     -------------------------------------- - 12.2/12.8 MB 2.7 MB/s eta 0:00:01
     -------------------------------------- - 12.3/12.8 MB 2.7 MB/s eta 0:00:01
     -------------------------------------- - 12.3/12.8 MB 2.7 MB/s eta 0:00:01
     -------------------------------------- - 12.4/12.8 MB 2.6 MB/s eta 0:00:01
     ---------------------------------------  12.6/12.8 MB 2.6 MB/s eta 0:00:01
     ---------------------------------------  12.8/12.8 MB 2.7 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 2.7 MB/s eta 0:00:00
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [5]:
!pip install pdfminer.six

Collecting pdfminer.six
  Downloading pdfminer_six-20260107-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: charset-normalizer>=2.0.0 in c:\users\dell\anaconda3\lib\site-packages (from pdfminer.six) (2.0.4)
Requirement already satisfied: cryptography>=36.0.0 in c:\users\dell\anaconda3\lib\site-packages (from pdfminer.six) (42.0.2)
Requirement already satisfied: cffi>=1.12 in c:\users\dell\anaconda3\lib\site-packages (from cryptography>=36.0.0->pdfminer.six) (2.0.0)
Requirement already satisfied: pycparser in c:\users\dell\anaconda3\lib\site-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six) (2.21)
Downloading pdfminer_six-20260107-py3-none-any.whl (6.6 MB)
   ---------------------------------------- 0.0/6.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.6 MB 217.9 kB/s eta 0:00:31
   ---------------------------------------- 0.1/6.6 MB 363.1 kB/s eta 0:00:18
   - -------------------------------------- 0.3/6.6 MB 1.6 MB/s eta 0:00:04
   --- ------------------------------------ 0.6/6.6 MB 2.7 MB/s eta 0:00:03
   ------ --------------------------------- 1.0/6.6 MB 3.4 MB/s eta 0:00:02
   ------- -------------------------------- 1.2/6.6 MB 3.5 MB/s eta 0:00:02
   ------- -------------------------------- 1.3/6.6 MB 3.4 MB/s eta 0:00:02
   ------- -------------------------------- 1.3/6.6 MB 3.4 MB/s eta 0:00:02
   -------- ------------------------------- 1.4/6.6 MB 2.9 MB/s eta 0:00:02
   ----------- ---------------------------- 1.9/6.6 MB 3.6 MB/s eta 0:00:02
   ------------ --------------------------- 2.1/6.6 MB 3.6 MB/s eta 0:00:02
   ------------- -------------------------- 2.3/6.6 MB 3.6 MB/s eta 0:00:02
   -------------- ------------------------- 2.4/6.6 MB 3.6 MB/s eta 0:00:02
   --------------- ------------------------ 2.6/6.6 MB 3.6 MB/s eta 0:00:02
   ---------------- ----------------------- 2.7/6.6 MB 3.6 MB/s eta 0:00:02
   ----------------- ---------------------- 2.9/6.6 MB 3.7 MB/s eta 0:00:01
   ------------------ --------------------- 3.1/6.6 MB 3.7 MB/s eta 0:00:01
   -------------------- ------------------- 3.3/6.6 MB 3.7 MB/s eta 0:00:01
   --------------------- ------------------ 3.5/6.6 MB 3.7 MB/s eta 0:00:01
   ---------------------- ----------------- 3.7/6.6 MB 3.7 MB/s eta 0:00:01
   ----------------------- ---------------- 3.9/6.6 MB 3.7 MB/s eta 0:00:01
   ------------------------ --------------- 4.1/6.6 MB 3.7 MB/s eta 0:00:01
   ------------------------- -------------- 4.2/6.6 MB 3.8 MB/s eta 0:00:01
   -------------------------- ------------- 4.4/6.6 MB 3.8 MB/s eta 0:00:01
   --------------------------- ------------ 4.6/6.6 MB 3.7 MB/s eta 0:00:01
   ---------------------------- ----------- 4.8/6.6 MB 3.8 MB/s eta 0:00:01
   ----------------------------- ---------- 4.9/6.6 MB 3.8 MB/s eta 0:00:01
   ------------------------------ --------- 5.1/6.6 MB 3.7 MB/s eta 0:00:01
   -------------------------------- ------- 5.3/6.6 MB 3.8 MB/s eta 0:00:01
   --------------------------------- ------ 5.5/6.6 MB 3.8 MB/s eta 0:00:01
   --------------------------------- ------ 5.6/6.6 MB 3.8 MB/s eta 0:00:01
   --------------------------------- ------ 5.6/6.6 MB 3.8 MB/s eta 0:00:01
   ------------------------------------ --- 6.0/6.6 MB 3.8 MB/s eta 0:00:01
   ------------------------------------- -- 6.2/6.6 MB 3.8 MB/s eta 0:00:01
   -------------------------------------- - 6.4/6.6 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------  6.6/6.6 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 6.6/6.6 MB 3.8 MB/s eta 0:00:00
Installing collected packages: pdfminer.six
Successfully installed pdfminer.six-20260107

In [7]:
import pandas as pd
import numpy as np
import spacy
import re
import os

from pdfminer.high_level import extract_text
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [10]:
jobs = pd.read_csv(r"C:\Users\DELL\Documents\AI\AI_Resume_Screener\dataset\job_descriptions_dataset.csv")
jobs.head()

,job_title,skills,job_description
0,Data Scientist,"Python, Machine Learning, SQL, Statistics, Pan...","Analyze large datasets, build predictive model..."
1,Machine Learning Engineer,"Python, Machine Learning, TensorFlow, PyTorch,...","Design, build, and deploy scalable machine lea..."
2,Data Analyst,"SQL, Excel, Python, Data Visualization, Tablea...","Analyze business data, build dashboards, and g..."
3,AI Engineer,"Python, Deep Learning, TensorFlow, PyTorch, NL...",Develop artificial intelligence systems using ...
4,Python Developer,"Python, Django, Flask, APIs, SQL, Git",Develop backend systems and APIs using Python ...

In [12]:
#Select Job Role
job_role = "Data Scientist"
job_description = jobs[jobs['job_title']==job_role]['skills'].iloc[0]
print(job_description)

Python, Machine Learning, SQL, Statistics, Pandas, Scikit-learn, Data Visualization, NLP

In [13]:
#Extract Text From Resume
def extract_resume_text(file_path):
    text = extract_text(file_path)
    return text

In [14]:
resume_text = extract_resume_text(r"C:\Users\DELL\Documents\AI\AI_Resume_Screener\dataset\resumes\resume1.pdf")
print(resume_text[:500])

Amit Sharma

Role: Data Scientist

Professional Summary

Worked on predictive modeling and data analysis projects using Python and machine learning.

Skills

Python

Machine Learning

SQL

Pandas

Scikit-learn

Data Visualization

Statistics

NLP

In [15]:
#Clean Resume Text
def clean_text(text):

    text = re.sub(r'\n',' ',text)

    text = re.sub(r'[^A-Za-z ]','',text)

    text = text.lower()

    return text

In [16]:
#Load NLP Model
nlp = spacy.load("en_core_web_sm")

In [17]:
#Skill Extraction
skills_list = [
    "python","machine learning","sql","deep learning",
    "data analysis","nlp","tensorflow","pandas","java"
]

def extract_skills(text):

    doc = nlp(text)

    found_skills = []

    for token in doc:

        if token.text.lower() in skills_list:

            found_skills.append(token.text)

    return list(set(found_skills))

In [18]:
#Similarity Model
def calculate_similarity(resume, job_description):

    vectorizer = TfidfVectorizer()

    tfidf_matrix = vectorizer.fit_transform([resume, job_description])

    score = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2])

    return score[0][0]

In [ ]:
#Rank Multiple Resumes
resume_folder = r"C:\Users\DELL\Documents\AI\AI_Resume_Screener\dataset\resumes"

results = []

for file in os.listdir(resume_folder):
    file_path = os.path.join(resume_folder,file)
    resume_text = extract_resume_text(file_path)
    cleaned = clean_text(resume_text)
    score = calculate_similarity(cleaned, job_description)
    results.append((file,score))

In [21]:
#Sort Candidates
ranked = sorted(results,key=lambda x:x[1],reverse=True)
for name,score in ranked:
    print(name,score)

resume1.pdf 0.4880767302742728
resume3.pdf 0.22794900336940474
resume4.pdf 0.19800517126347725
resume5.pdf 0.13387083899186267
resume2.pdf 0.11671770522446966

In [22]:
#Show Results Table
df = pd.DataFrame(ranked,columns=["Candidate Resume","Match Score"])
df

  Candidate Resume  Match Score
0      resume1.pdf     0.488077
1      resume3.pdf     0.227949
2      resume4.pdf     0.198005
3      resume5.pdf     0.133871
4      resume2.pdf     0.116718